sudo: true

language: go
go:
  - 1.9

before_install:
  - go get -t -v ./...
  - go get github.com/mattn/goveralls

script:
  - go test -coverprofile=partial.coverprofile
  - goveralls -coverprofile=partial.coverprofile -service=travis-ci
